### ISSUE TITLE
Add code examples for basic operations in README.md

### ISSUE THREAD

**Issue by rtb-12** [IMGIITRoorkee/Memoria#18]
We need to enhance the project's **README.md** file by including simple primitive methods like `Read`,`Write`,`Keys`,`Erase`,`Put` examples for basic operations. This will make it easier for new users and contributors to understand and utilize the project.  

### Tasks  
- [ ] Add a **Read Example** to the README.  
- [ ] Add a **Write Example** to the README.  
- [ ] Add a **Delete Example** to the README.  
- [ ] Add a **Keys Listing Example** to the README.  

### Additional Notes  
- Ensure examples are concise and beginner-friendly.  
- Use comments in the code snippets to explain each step.  
- Validate the examples to confirm they work with the current implementation of the project. Add them to an `examples` directory
