### ISSUE TITLE
Make memoria cli

### ISSUE THREAD

**Issue by 0xnullifier** [IMGIITRoorkee/Memoria#24]
A cli is nothing but a way to call the golang function from the command line. Use famous libraries `cobra` or more to make the cli.

More cli issues wil be opened  up as more functionalities are added to the codebase. Add code to [cli.go](https://github.com/IMGIITRoorkee/Memoria_Simple/blob/main/cli.go)

### Basic Commands to Implement:
```bash
# Store a value
memoria add/put <key> <value> # 

# Get a value
memoria get <key>

# Initialize store
memoria init --path <directory> [--cache-size <size>] # this should init everthing in the base dir and restore the indexer and all to the initial state essentialy call the `memoria.New(o)` with some valid options
```

**Tasks**
- [ ] Setup initial cli code
- [ ]  code for `init` command
- [ ] code for `get` and `add`

**Comment by Ritchie6** [comment]
I'm working on this issue #24
