### ISSUE TITLE
Add Basic Logging System using zap/zerolog

### ISSUE THREAD

**Issue by rtb-12** [IMGIITRoorkee/Memoria#25]
Add basic logging to track core operations and errors in Memoria using a structured logging library.

**Required Logging Points**
1. Core Operations in [`memoria.go`](memoria.go):
   - Read/Write operations
   - Cache hits/misses
   - File operations
   - Error conditions
   
**Implementation Details**
Add logger to the Memoria struct:
```go
type Options struct {
    // existing fields
    Logger Logger // Interface for logging
}

type Logger interface {
    Info(msg string, fields ...Field)
    Error(msg string, fields ...Field)
}
```

**Learning Resources**
1. [Go zap logger](https://github.com/uber-go/zap)
2. [Zerolog docs](https://github.com/rs/zerolog)

**Tasks**
- [ ] Add logger interface
- [ ] Implement basic logging in:
  - [ ] `Read`
  - [ ] `Write`
- [ ] `cache.go` operations
- [ ] Add configuration options
- [ ] Update documentation
